version: "3"
services:


  chatbot:
    build: .
    container_name: chatbot
    restart: always
    ports:
      - 5000:5000
    networks:
      - chatbot-network
networks:
  chatbot-network:
    driver: bridge
