version: "3.3"
services:

  chatbot:
    build: .
    container_name: chatbot
    restart: always
    volumes:
      - chatbot-logs:/logs
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - chatbot-network

  db:
    image: mysql:5.7
    container_name: chatbot-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
    networks:
      - chatbot-network
    restart: unless-stopped

networks:
  chatbot-network:
    driver: bridge

volumes:
  mysql:
  chatbot-logs:
